// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	"github.com/bbdLe/iGame/comm"
	"github.com/bbdLe/iGame/comm/codec"
	_ "github.com/bbdLe/iGame/comm/codec/gogopb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	"reflect"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProtoID int32

const (
	ProtoID_CS_CMD_START               ProtoID = 0
	ProtoID_CS_CMD_LOGIN_REQ           ProtoID = 1
	ProtoID_CS_CMD_LOGIN_RES           ProtoID = 2
	ProtoID_CS_CMD_CHAT_REQ            ProtoID = 3
	ProtoID_CS_CMD_CHAT_RES            ProtoID = 4
	ProtoID_CS_CMD_VERIFY_REQ          ProtoID = 5
	ProtoID_CS_CMD_VERIFY_RES          ProtoID = 6
	ProtoID_CS_CMD_TRANSMIT_REQ        ProtoID = 7
	ProtoID_CS_CMD_TRANSMIT_RES        ProtoID = 8
	ProtoID_CS_CMD_KICK_CONN_REQ       ProtoID = 9
	ProtoID_CS_CMD_KICK_CONN_RES       ProtoID = 10
	ProtoID_CS_CMD_CONN_DISCONNECT_REQ ProtoID = 11
	ProtoID_CS_CMD_CONN_DISCONNECT_RES ProtoID = 12
	ProtoID_CS_CMD_HEART_BETA_REQ      ProtoID = 13
	ProtoID_CS_CMD_HEART_BETA_RES      ProtoID = 14
	ProtoID_CS_CMD_CREATE_ROOM_REQ     ProtoID = 15
	ProtoID_CS_CMD_CREATE_ROOM_RES     ProtoID = 16
)

var ProtoID_name = map[int32]string{
	0:  "CS_CMD_START",
	1:  "CS_CMD_LOGIN_REQ",
	2:  "CS_CMD_LOGIN_RES",
	3:  "CS_CMD_CHAT_REQ",
	4:  "CS_CMD_CHAT_RES",
	5:  "CS_CMD_VERIFY_REQ",
	6:  "CS_CMD_VERIFY_RES",
	7:  "CS_CMD_TRANSMIT_REQ",
	8:  "CS_CMD_TRANSMIT_RES",
	9:  "CS_CMD_KICK_CONN_REQ",
	10: "CS_CMD_KICK_CONN_RES",
	11: "CS_CMD_CONN_DISCONNECT_REQ",
	12: "CS_CMD_CONN_DISCONNECT_RES",
	13: "CS_CMD_HEART_BETA_REQ",
	14: "CS_CMD_HEART_BETA_RES",
	15: "CS_CMD_CREATE_ROOM_REQ",
	16: "CS_CMD_CREATE_ROOM_RES",
}

var ProtoID_value = map[string]int32{
	"CS_CMD_START":               0,
	"CS_CMD_LOGIN_REQ":           1,
	"CS_CMD_LOGIN_RES":           2,
	"CS_CMD_CHAT_REQ":            3,
	"CS_CMD_CHAT_RES":            4,
	"CS_CMD_VERIFY_REQ":          5,
	"CS_CMD_VERIFY_RES":          6,
	"CS_CMD_TRANSMIT_REQ":        7,
	"CS_CMD_TRANSMIT_RES":        8,
	"CS_CMD_KICK_CONN_REQ":       9,
	"CS_CMD_KICK_CONN_RES":       10,
	"CS_CMD_CONN_DISCONNECT_REQ": 11,
	"CS_CMD_CONN_DISCONNECT_RES": 12,
	"CS_CMD_HEART_BETA_REQ":      13,
	"CS_CMD_HEART_BETA_RES":      14,
	"CS_CMD_CREATE_ROOM_REQ":     15,
	"CS_CMD_CREATE_ROOM_RES":     16,
}

func (x ProtoID) String() string {
	return proto.EnumName(ProtoID_name, int32(x))
}

func (ProtoID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

//[id:CS_CMD_LOGIN_REQ]
type LoginReq struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	AuthTime             int64    `protobuf:"varint,5,opt,name=AuthTime,proto3" json:"AuthTime,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *LoginReq) GetAuthTime() int64 {
	if m != nil {
		return m.AuthTime
	}
	return 0
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// [id:CS_CMD_LOGIN_RES]
type LoginRes struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}
func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *LoginRes) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

// [id:CS_CMD_VERIFY_REQ]
type VerifyReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}
func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

// [id:CS_CMD_VERIFY_RES]
type VerifyRes struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRes) Reset()         { *m = VerifyRes{} }
func (m *VerifyRes) String() string { return proto.CompactTextString(m) }
func (*VerifyRes) ProtoMessage()    {}
func (*VerifyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}
func (m *VerifyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRes.Unmarshal(m, b)
}
func (m *VerifyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRes.Marshal(b, m, deterministic)
}
func (m *VerifyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRes.Merge(m, src)
}
func (m *VerifyRes) XXX_Size() int {
	return xxx_messageInfo_VerifyRes.Size(m)
}
func (m *VerifyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRes.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRes proto.InternalMessageInfo

func (m *VerifyRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *VerifyRes) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

// [id:CS_CMD_TRANSMIT_REQ]
type TransmitReq struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	ClientId             int64    `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitReq) Reset()         { *m = TransmitReq{} }
func (m *TransmitReq) String() string { return proto.CompactTextString(m) }
func (*TransmitReq) ProtoMessage()    {}
func (*TransmitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}
func (m *TransmitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitReq.Unmarshal(m, b)
}
func (m *TransmitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitReq.Marshal(b, m, deterministic)
}
func (m *TransmitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitReq.Merge(m, src)
}
func (m *TransmitReq) XXX_Size() int {
	return xxx_messageInfo_TransmitReq.Size(m)
}
func (m *TransmitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitReq proto.InternalMessageInfo

func (m *TransmitReq) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *TransmitReq) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *TransmitReq) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// [id:CS_CMD_TRANSMIT_RES]
type TransmitRes struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	ClientId             int64    `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitRes) Reset()         { *m = TransmitRes{} }
func (m *TransmitRes) String() string { return proto.CompactTextString(m) }
func (*TransmitRes) ProtoMessage()    {}
func (*TransmitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}
func (m *TransmitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitRes.Unmarshal(m, b)
}
func (m *TransmitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitRes.Marshal(b, m, deterministic)
}
func (m *TransmitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitRes.Merge(m, src)
}
func (m *TransmitRes) XXX_Size() int {
	return xxx_messageInfo_TransmitRes.Size(m)
}
func (m *TransmitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitRes.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitRes proto.InternalMessageInfo

func (m *TransmitRes) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *TransmitRes) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *TransmitRes) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// [id:CS_CMD_CHAT_REQ ]
type ChatReq struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatReq) Reset()         { *m = ChatReq{} }
func (m *ChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatReq) ProtoMessage()    {}
func (*ChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}
func (m *ChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatReq.Unmarshal(m, b)
}
func (m *ChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatReq.Marshal(b, m, deterministic)
}
func (m *ChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatReq.Merge(m, src)
}
func (m *ChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatReq.Size(m)
}
func (m *ChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatReq proto.InternalMessageInfo

func (m *ChatReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// [id:CS_CMD_CHAT_RES]
type ChatRes struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRes) Reset()         { *m = ChatRes{} }
func (m *ChatRes) String() string { return proto.CompactTextString(m) }
func (*ChatRes) ProtoMessage()    {}
func (*ChatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}
func (m *ChatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRes.Unmarshal(m, b)
}
func (m *ChatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRes.Marshal(b, m, deterministic)
}
func (m *ChatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRes.Merge(m, src)
}
func (m *ChatRes) XXX_Size() int {
	return xxx_messageInfo_ChatRes.Size(m)
}
func (m *ChatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRes proto.InternalMessageInfo

func (m *ChatRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ChatRes) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

// [id:CS_CMD_KICK_CONN_REQ]
type KickConnReq struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickConnReq) Reset()         { *m = KickConnReq{} }
func (m *KickConnReq) String() string { return proto.CompactTextString(m) }
func (*KickConnReq) ProtoMessage()    {}
func (*KickConnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}
func (m *KickConnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickConnReq.Unmarshal(m, b)
}
func (m *KickConnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickConnReq.Marshal(b, m, deterministic)
}
func (m *KickConnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickConnReq.Merge(m, src)
}
func (m *KickConnReq) XXX_Size() int {
	return xxx_messageInfo_KickConnReq.Size(m)
}
func (m *KickConnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KickConnReq.DiscardUnknown(m)
}

var xxx_messageInfo_KickConnReq proto.InternalMessageInfo

func (m *KickConnReq) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// [id:CS_CMD_KICK_CONN_RES]
type KickConnRes struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickConnRes) Reset()         { *m = KickConnRes{} }
func (m *KickConnRes) String() string { return proto.CompactTextString(m) }
func (*KickConnRes) ProtoMessage()    {}
func (*KickConnRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}
func (m *KickConnRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickConnRes.Unmarshal(m, b)
}
func (m *KickConnRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickConnRes.Marshal(b, m, deterministic)
}
func (m *KickConnRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickConnRes.Merge(m, src)
}
func (m *KickConnRes) XXX_Size() int {
	return xxx_messageInfo_KickConnRes.Size(m)
}
func (m *KickConnRes) XXX_DiscardUnknown() {
	xxx_messageInfo_KickConnRes.DiscardUnknown(m)
}

var xxx_messageInfo_KickConnRes proto.InternalMessageInfo

func (m *KickConnRes) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *KickConnRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

// [id:CS_CMD_CONN_DISCONNECT_REQ]
type ConnDisconnectReq struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnDisconnectReq) Reset()         { *m = ConnDisconnectReq{} }
func (m *ConnDisconnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnDisconnectReq) ProtoMessage()    {}
func (*ConnDisconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}
func (m *ConnDisconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnDisconnectReq.Unmarshal(m, b)
}
func (m *ConnDisconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnDisconnectReq.Marshal(b, m, deterministic)
}
func (m *ConnDisconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnDisconnectReq.Merge(m, src)
}
func (m *ConnDisconnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnDisconnectReq.Size(m)
}
func (m *ConnDisconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnDisconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnDisconnectReq proto.InternalMessageInfo

func (m *ConnDisconnectReq) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

// [id:CS_CMD_CONN_DISCONNECT_RES]
type ConnDisconnectRes struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnDisconnectRes) Reset()         { *m = ConnDisconnectRes{} }
func (m *ConnDisconnectRes) String() string { return proto.CompactTextString(m) }
func (*ConnDisconnectRes) ProtoMessage()    {}
func (*ConnDisconnectRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}
func (m *ConnDisconnectRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnDisconnectRes.Unmarshal(m, b)
}
func (m *ConnDisconnectRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnDisconnectRes.Marshal(b, m, deterministic)
}
func (m *ConnDisconnectRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnDisconnectRes.Merge(m, src)
}
func (m *ConnDisconnectRes) XXX_Size() int {
	return xxx_messageInfo_ConnDisconnectRes.Size(m)
}
func (m *ConnDisconnectRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnDisconnectRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConnDisconnectRes proto.InternalMessageInfo

func (m *ConnDisconnectRes) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ConnDisconnectRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

// [id:CS_CMD_HEART_BETA_REQ ]
type HeartBeatReq struct {
	Reverse              []byte   `protobuf:"bytes,1,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}
func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (m *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(m, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetReverse() []byte {
	if m != nil {
		return m.Reverse
	}
	return nil
}

// [id:CS_CMD_HEART_BETA_RES ]
type HeartBeatRes struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRes) Reset()         { *m = HeartBeatRes{} }
func (m *HeartBeatRes) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRes) ProtoMessage()    {}
func (*HeartBeatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}
func (m *HeartBeatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRes.Unmarshal(m, b)
}
func (m *HeartBeatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRes.Marshal(b, m, deterministic)
}
func (m *HeartBeatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRes.Merge(m, src)
}
func (m *HeartBeatRes) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRes.Size(m)
}
func (m *HeartBeatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRes proto.InternalMessageInfo

func (m *HeartBeatRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

// [id:CS_CMD_CREATE_ROOM_REQ ]
type CreateRoomReq struct {
	Reverse              []byte   `protobuf:"bytes,1,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}
func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(m, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

func (m *CreateRoomReq) GetReverse() []byte {
	if m != nil {
		return m.Reverse
	}
	return nil
}

// [id:CS_CMD_CREATE_ROOM_RES ]
type CreateRoomRes struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RoomId               int64    `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRes) Reset()         { *m = CreateRoomRes{} }
func (m *CreateRoomRes) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRes) ProtoMessage()    {}
func (*CreateRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}
func (m *CreateRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRes.Unmarshal(m, b)
}
func (m *CreateRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRes.Marshal(b, m, deterministic)
}
func (m *CreateRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRes.Merge(m, src)
}
func (m *CreateRoomRes) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRes.Size(m)
}
func (m *CreateRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRes proto.InternalMessageInfo

func (m *CreateRoomRes) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *CreateRoomRes) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.ProtoID", ProtoID_name, ProtoID_value)
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto.RegisterType((*VerifyReq)(nil), "proto.VerifyReq")
	proto.RegisterType((*VerifyRes)(nil), "proto.VerifyRes")
	proto.RegisterType((*TransmitReq)(nil), "proto.TransmitReq")
	proto.RegisterType((*TransmitRes)(nil), "proto.TransmitRes")
	proto.RegisterType((*ChatReq)(nil), "proto.ChatReq")
	proto.RegisterType((*ChatRes)(nil), "proto.ChatRes")
	proto.RegisterType((*KickConnReq)(nil), "proto.KickConnReq")
	proto.RegisterType((*KickConnRes)(nil), "proto.KickConnRes")
	proto.RegisterType((*ConnDisconnectReq)(nil), "proto.ConnDisconnectReq")
	proto.RegisterType((*ConnDisconnectRes)(nil), "proto.ConnDisconnectRes")
	proto.RegisterType((*HeartBeatReq)(nil), "proto.HeartBeatReq")
	proto.RegisterType((*HeartBeatRes)(nil), "proto.HeartBeatRes")
	proto.RegisterType((*CreateRoomReq)(nil), "proto.CreateRoomReq")
	proto.RegisterType((*CreateRoomRes)(nil), "proto.CreateRoomRes")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5f, 0x4f, 0xdb, 0x3e,
	0x14, 0xfd, 0xa5, 0xa5, 0x69, 0x7b, 0x29, 0x3f, 0x8c, 0xf9, 0x17, 0x98, 0x34, 0xa1, 0xec, 0x05,
	0x78, 0x98, 0x26, 0xed, 0x69, 0x0f, 0xdb, 0x14, 0xd2, 0x6c, 0x44, 0xa5, 0x74, 0x73, 0x22, 0xa4,
	0x49, 0x93, 0xa2, 0x2c, 0x31, 0x21, 0x82, 0xc4, 0xcc, 0x36, 0x48, 0xfb, 0x32, 0xfb, 0x12, 0xfb,
	0x82, 0x93, 0x9d, 0xa4, 0xa3, 0x03, 0x8a, 0x54, 0xed, 0x29, 0x39, 0xe7, 0xdc, 0x7b, 0xee, 0xf1,
	0xad, 0x1b, 0xe8, 0x17, 0x22, 0x7b, 0x79, 0xcd, 0x99, 0x64, 0xb8, 0xa3, 0x1f, 0xf6, 0x4f, 0x03,
	0x7a, 0x27, 0x2c, 0xcb, 0x4b, 0x42, 0xbf, 0x63, 0x0b, 0xba, 0xb7, 0x94, 0x8b, 0x9c, 0x95, 0x96,
	0xb1, 0x67, 0xec, 0xf7, 0x49, 0x03, 0xf1, 0x2e, 0xf4, 0xae, 0xaf, 0x62, 0x79, 0xce, 0x78, 0x61,
	0xb5, 0xb4, 0x34, 0xc5, 0x18, 0x41, 0xfb, 0x26, 0x4f, 0xad, 0xb6, 0xa6, 0xd5, 0xab, 0xf2, 0x49,
	0x2e, 0xe2, 0xb2, 0xa4, 0x57, 0xd6, 0x52, 0xe5, 0x53, 0x43, 0xe5, 0xe3, 0xdc, 0xc8, 0x8b, 0x30,
	0x2f, 0xa8, 0xd5, 0xd9, 0x33, 0xf6, 0xdb, 0x64, 0x8a, 0xf1, 0x06, 0x74, 0x24, 0xbb, 0xa4, 0xa5,
	0x65, 0xea, 0x9e, 0x0a, 0xd8, 0xef, 0xa6, 0xf9, 0x04, 0xde, 0x81, 0x1e, 0xa7, 0x32, 0x4a, 0x58,
	0x4a, 0x75, 0xc0, 0x0e, 0xe9, 0x72, 0x2a, 0x5d, 0x96, 0x52, 0xbc, 0x0d, 0xea, 0x35, 0x2a, 0x44,
	0x56, 0xe7, 0x33, 0x39, 0x95, 0x63, 0x91, 0xd9, 0x6f, 0xa0, 0x7f, 0x46, 0x79, 0x7e, 0xfe, 0x43,
	0x1d, 0x70, 0x3a, 0xc2, 0xb8, 0x33, 0x02, 0x6f, 0x81, 0x29, 0x28, 0xbf, 0xa5, 0xbc, 0x69, 0xad,
	0x90, 0xfd, 0xfe, 0x4f, 0xeb, 0x62, 0xb3, 0xbf, 0xc2, 0x72, 0xc8, 0xe3, 0x52, 0x14, 0xb9, 0x54,
	0xd3, 0x37, 0xc1, 0x2c, 0x44, 0x16, 0xe5, 0x69, 0x6d, 0xd0, 0x29, 0x44, 0xe6, 0xa7, 0xca, 0x59,
	0xd1, 0x69, 0x2c, 0x63, 0xdd, 0x3f, 0x20, 0xdd, 0x42, 0x64, 0xc3, 0x58, 0xc6, 0xf8, 0x19, 0xf4,
	0x93, 0xab, 0x9c, 0x96, 0x32, 0xaa, 0x17, 0xdc, 0x26, 0xbd, 0x8a, 0xf0, 0xd3, 0x59, 0x77, 0xf1,
	0xaf, 0xdd, 0x5f, 0x40, 0xd7, 0xbd, 0x88, 0x65, 0x7d, 0x2d, 0x12, 0x56, 0x4a, 0x5a, 0xca, 0xe6,
	0x5a, 0xd4, 0xd0, 0x7e, 0xdb, 0x14, 0x2d, 0xb6, 0x9f, 0x43, 0x58, 0x1e, 0xe5, 0xc9, 0xa5, 0xcb,
	0x4a, 0x7d, 0xfd, 0x66, 0xf2, 0x18, 0x7f, 0xe5, 0xf1, 0xee, 0xd6, 0x8a, 0xb9, 0xb5, 0x33, 0x59,
	0x5a, 0x33, 0x59, 0xec, 0x57, 0xb0, 0xa6, 0x2c, 0x86, 0xb9, 0x48, 0x58, 0x59, 0xd2, 0x44, 0x3e,
	0x39, 0x78, 0x74, 0xbf, 0x63, 0xf1, 0xf1, 0xfb, 0x30, 0x38, 0xa6, 0x31, 0x97, 0x47, 0x74, 0xba,
	0x5a, 0x4e, 0xd5, 0x9f, 0xac, 0x5a, 0xda, 0x80, 0x34, 0xd0, 0x3e, 0x98, 0xa9, 0x9c, 0xb7, 0x5f,
	0xfb, 0x00, 0x56, 0x5c, 0x4e, 0x63, 0x49, 0x09, 0x63, 0xc5, 0x7c, 0x57, 0x77, 0xb6, 0xf4, 0xc9,
	0x9f, 0x8d, 0xb1, 0x42, 0x9d, 0xb0, 0xa5, 0x4f, 0x68, 0x2a, 0xe8, 0xa7, 0x87, 0xbf, 0xda, 0xd0,
	0xfd, 0xa4, 0xbe, 0x1e, 0xfe, 0x10, 0x23, 0x18, 0xb8, 0x41, 0xe4, 0x8e, 0x87, 0x51, 0x10, 0x3a,
	0x24, 0x44, 0xff, 0xe1, 0x0d, 0x40, 0x35, 0x73, 0x32, 0xf9, 0xe8, 0x9f, 0x46, 0xc4, 0xfb, 0x8c,
	0x8c, 0x07, 0xd8, 0x00, 0xb5, 0xf0, 0x3a, 0xac, 0xd6, 0xac, 0x7b, 0xec, 0x84, 0xba, 0xb4, 0x7d,
	0x9f, 0x0c, 0xd0, 0x12, 0xde, 0x84, 0xb5, 0x9a, 0x3c, 0xf3, 0x88, 0xff, 0xe1, 0x8b, 0xae, 0xed,
	0x3c, 0x44, 0x07, 0xc8, 0xc4, 0xdb, 0xb0, 0x5e, 0xd3, 0x21, 0x71, 0x4e, 0x83, 0xb1, 0x5f, 0x79,
	0x77, 0x1f, 0x16, 0x02, 0xd4, 0xc3, 0x16, 0x6c, 0xd4, 0xc2, 0xc8, 0x77, 0x47, 0x91, 0x3b, 0x39,
	0xad, 0x92, 0xf7, 0x1f, 0x51, 0x02, 0x04, 0xf8, 0x39, 0xec, 0x36, 0x41, 0x15, 0x39, 0xf4, 0x03,
	0xf5, 0xf4, 0xdc, 0x6a, 0xd8, 0xf2, 0x5c, 0x3d, 0x40, 0x03, 0xbc, 0x03, 0x9b, 0xb5, 0x7e, 0xec,
	0x39, 0x24, 0x8c, 0x8e, 0xbc, 0xd0, 0xd1, 0xad, 0x2b, 0x8f, 0x49, 0x01, 0xfa, 0x1f, 0xef, 0xc2,
	0x56, 0xe3, 0x4a, 0x3c, 0x27, 0xf4, 0x22, 0x32, 0x99, 0x8c, 0x75, 0xdb, 0xea, 0xa3, 0x5a, 0x80,
	0xd0, 0x37, 0x53, 0x7f, 0xf0, 0x5f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x31, 0x38, 0xcb, 0xa3,
	0x04, 0x06, 0x00, 0x00,
}

func init() {

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_LOGIN_REQ),
		Type:  reflect.TypeOf((*LoginReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_LOGIN_RES),
		Type:  reflect.TypeOf((*LoginRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_VERIFY_REQ),
		Type:  reflect.TypeOf((*VerifyReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_VERIFY_RES),
		Type:  reflect.TypeOf((*VerifyRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_TRANSMIT_REQ),
		Type:  reflect.TypeOf((*TransmitReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_TRANSMIT_RES),
		Type:  reflect.TypeOf((*TransmitRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CHAT_REQ),
		Type:  reflect.TypeOf((*ChatReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CHAT_RES),
		Type:  reflect.TypeOf((*ChatRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_KICK_CONN_REQ),
		Type:  reflect.TypeOf((*KickConnReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_KICK_CONN_RES),
		Type:  reflect.TypeOf((*KickConnRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CONN_DISCONNECT_REQ),
		Type:  reflect.TypeOf((*ConnDisconnectReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CONN_DISCONNECT_RES),
		Type:  reflect.TypeOf((*ConnDisconnectRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_HEART_BETA_REQ),
		Type:  reflect.TypeOf((*HeartBeatReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_HEART_BETA_RES),
		Type:  reflect.TypeOf((*HeartBeatRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CREATE_ROOM_REQ),
		Type:  reflect.TypeOf((*CreateRoomReq)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

	comm.RegMessageMeta(&comm.MessageMeta{
		MsgId: int(ProtoID_CS_CMD_CREATE_ROOM_RES),
		Type:  reflect.TypeOf((*CreateRoomRes)(nil)).Elem(),
		Codec: codec.MustGetCodec("gogopb"),
	})

}
